#!/bin/bash

cd $OPENSHIFT_REPO_DIR
mkdir temp_dir
cd temp_dir
rm *.pid
cd $OPENSHIFT_REPO_DIR
celery multi stop worker1
celery multi start worker1 \
	-A tasks \
	--pidfile="temp_dir/%n.pid" \
    --logfile="%n.log"
